[tools]
go = "latest"
java = "latest"
node = "latest"
dotnet = "latest"
rust = "latest"
bun = "latest"
clang = "latest"
mold = "latest"
task = "latest"
python = "3.12.12"
air = "latest"
lua = "5.1"


